name: flutter_drug_registry
description: A Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.1.0+7

environment:
  sdk: '^3.7.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  json_serializable: ^6.6.1
  json_annotation: ^4.8.0
  build_runner: ^2.3.3
  http: ^0.13.5
  get_it: ^7.2.0
  geolocator: ^9.0.2
  provider: ^6.0.5
  flutter_svg: ^2.0.5
  loading_animation_widget: ^1.2.0+4
  url_launcher: ^6.1.10
  shared_preferences: ^2.1.0
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  bloc: ^8.1.4
  rxdart: ^0.28.0
  collection: ^1.18.0
  intl: ^0.19.0
  package_info_plus: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  image_path: "assets/icon/icon.png"
  android: true
  ios: true

flutter:

  uses-material-design: true

  assets:
    - assets/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21
